### ISSUE TITLE
WebUI hang or no further handle of request from web ui

### ISSUE THREAD

**Issue by chongy076** [nomic-ai/gpt4all-ui#130]
## Expected Behavior
should continue running after system 
### Human:The model is halucinating
Client disconnected
Client connected
Client disconnected

## Current Behavior
Please describe the behavior you are currently experiencing.

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. Step 1
  - load model https://huggingface.co/eachadea/ggml-vicuna-13b-4bit/resolve/main/ggml-vicuna-13b-4bit-rev1.bin
2. Step 2
 - ask data
 - date sales prev_sales diff\n 01/02/2013 459417 454904 4513\n01/03/2013 617382 459417 157965\n 01/04/2013 682274 617382 64892\n 01/05/2013 763242 682274 80968\n 01/06/2013 795597 763242 32355\n 01/07/2013 855922 795597 60325\n 01/08/2013 766761 855922 -89161\n 01/09/2013 689907 766761 -768540\n 01/10/2013 656587 689907 -33320\n 01/11/2013 692643 656587 36056\n
add margin column with 30% from  Sales values

4. Step 3
- see the AI generation , and wait session error 
# Load data into[2023-04-28 19:39:09,647] {_internal.py:186} ERROR - Error on request:
Traceback (most recent call last):
  File "C:\share\GPT4All\env\lib\site-packages\werkzeug\serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "C:\share\GPT4All\env\lib\site-packages\werkzeug\serving.py", line 325, in execute
    application_iter = app(environ, start_response)
  File "C:\share\GPT4All\env\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\share\GPT4All\env\lib\site-packages\flask_socketio\__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "C:\share\GPT4All\env\lib\site-packages\engineio\middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\share\GPT4All\env\lib\site-packages\socketio\server.py", line 607, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\share\GPT4All\env\lib\site-packages\engineio\server.py", line 408, in handle_request
    socket = self._get_socket(sid)
  File "C:\share\GPT4All\env\lib\site-packages\engineio\server.py", line 637, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
 DataFrame
## Possible Solution
- no idea yet.

## Context
Please provide any additional context about the issue.

## Screenshots
If applicable, add screenshots to help explain the issue.

![image](https://user-images.githubusercontent.com/50088438/235277391-9abd2732-d933-4221-a346-2a007ea50fb0.png)

![image](https://user-images.githubusercontent.com/50088438/235277426-e8915a26-4933-4875-b69e-02b1b53706b2.png)

**Comment by chongy076** [comment]
Problem addressed on wsgi server socket.
