### ISSUE TITLE
Startup fail with error: "no such table: message"

### ISSUE THREAD

**Issue by Earlh21** [nomic-ai/gpt4all-ui#143]
## Current Behavior
WebUI fails to start after fresh install, with the error:

```
Traceback (most recent call last):
  File "C:\Users\Idrialite\Downloads\gpt4all-ui\GPT4All\app.py", line 728, in <module>
    bot = Gpt4AllWebUI(app, socketio, config, personality, config_file_path)
  File "C:\Users\Idrialite\Downloads\gpt4all-ui\GPT4All\app.py", line 62, in __init__
    super().__init__(config, personality, config_file_path)
  File "C:\Users\Idrialite\Downloads\gpt4all-ui\GPT4All\pyGpt4All\api.py", line 40, in __init__
    self.db.populate()
  File "C:\Users\Idrialite\Downloads\gpt4all-ui\GPT4All\pyGpt4All\db.py", line 97, in populate
    cursor.execute("ALTER TABLE message ADD COLUMN type INT DEFAULT 0") # Added in V1
sqlite3.OperationalError: no such table: message
```

## Possible Solution
Fixed by adding a comma at the end of line 72 of pyGpt4all/db.py.

**Comment by ParisNeo** [comment]
Thanks. I was coding at 2am and forgot the comma. Thanks for testing the ui.

**Comment by ParisNeo** [comment]
Fixed by last update
