### ISSUE TITLE
Update Model Params triggers traceback and returns http 500

### ISSUE THREAD

**Issue by jasonwynn10** [nomic-ai/gpt4all-ui#45]
## Expected Behavior
Model parameters should be modifiable in the UI

## Current Behavior
An exception is thrown and returns http 500

## Steps to Reproduce

1. Modify the settings in the UI
2. Click on `Update Parameters`
3. See terminal

## Possible Solution
Key `top_k` must be sent with the POST request

## Context
```
[2023-04-08 10:02:39,351] {app.py:1744} ERROR - Exception on /update_model_params [POST]
Traceback (most recent call last):
  File "T:\gpt4all-ui\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "T:\gpt4all-ui\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "T:\gpt4all-ui\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "T:\gpt4all-ui\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "T:\gpt4all-ui\app.py", line 462, in update_model_params
    self.args.top_k = float(data["top_k"])
KeyError: 'top_k'
[2023-04-08 10:02:39,351] {_internal.py:224} INFO - 127.0.0.1 - - [08/Apr/2023 10:02:39] "POST /update_model_params HTTP/1.1" 500 -
```

**Comment by ParisNeo** [comment]
Issue fixed. Now parameters are applied correctly

**Comment by ParisNeo** [comment]
Thanks, I'll repare the bug
