### ISSUE TITLE
Latest UI update - no conversations

### ISSUE THREAD

**Issue by andzejsp** [nomic-ai/gpt4all-ui#78]
Did a git pull right nix and the old conversations are gonski.
Also the new conversation was read out in the console but didnt sho up in the UI :(

![image](https://user-images.githubusercontent.com/80409979/231748966-23cc47c2-890a-4c45-94bb-1ff6683b112b.png)

Was there a need to re run install.sh after git pull?

**Comment by andzejsp** [comment]
Also i cant add new conversations, and no conversation is showing in the UI

**Comment by ParisNeo** [comment]
Hi there. I have upgraded the code, can you please try again and tell me?

**Comment by ParisNeo** [comment]
The database format has changed to support multibranch discussions where you can create a different branch starting from a specific message. So I had to add an entry to the message called parent that allows me to create a more complex discussion that is more like a tree and not just a straight line. Ofcourse you will be able to have strait lines but you may want to explore many branches.

**Comment by andzejsp** [comment]
idk man, the buttons that supposed to export or created new conversations are not working.

And when i submit my prompt it crashes:
```
Received message : is jesus human?
[2023-04-13 19:55:07,216] {_internal.py:224} INFO - 192.168.0.106 - - [13/Apr/2023 19:55:07] "POST /bot HTTP/1.1" 200 -
[2023-04-13 19:55:07,217] {_internal.py:224} ERROR - Error on request:
Traceback (most recent call last):
  File "/home/sd2/gpt4all-ui/env/lib/python3.10/site-packages/werkzeug/serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "/home/sd2/gpt4all-ui/env/lib/python3.10/site-packages/werkzeug/serving.py", line 322, in execute
    for data in application_iter:
  File "/home/sd2/gpt4all-ui/env/lib/python3.10/site-packages/werkzeug/wsgi.py", line 500, in __next__
    return self._next()
  File "/home/sd2/gpt4all-ui/env/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 50, in _iter_encoded
    for item in iterable:
  File "/home/sd2/gpt4all-ui/env/lib/python3.10/site-packages/flask/helpers.py", line 149, in generator
    yield from gen
  File "/home/sd2/gpt4all-ui/env/lib/python3.10/site-packages/flask/helpers.py", line 149, in generator
    yield from gen
  File "/home/sd2/gpt4all-ui/app.py", line 258, in parse_to_prompt_stream
    self.prompt_message = [self.config["personality_conditionning"]]+ '\n'.join(self.full_message_list[-self.config["nb_messages_to_remember"]:])
KeyError: 'personality_conditionning'
```

**Comment by andzejsp** [comment]
well you could only save the database as all the other stuff can be changed to the app needs. My prompts are worthless, cuz i havent been able to prompt much but other people might be sad. :)

Also, maybe look into maybe using main branch for stable version, and dev branch for further development, so that people who want the bleeding edge could use dev branch and not complain that nothing is working :D.  This principle was working on one of the stable diffusion web UI - sygil :). Devs were pushing code like crazy to dev branch while the main was stable and working.

**Comment by ParisNeo** [comment]
Sorry folks. Save your database.db file somewhere. I'll probably do an upgrade script for old scripts.
You can also read your database using any sqlite tool.
The new database has a new structure that will allow having non linear discussions. You'll be able to go back in time and create a new branch.

**Comment by ParisNeo** [comment]
I'll start using dev vs main branches.
